### ISSUE TITLE
안드로이드 11 이상 앱 구동 안됨

### ISSUE THREAD

**Issue by PARKasd** [DesignOZ/FIXX-Unused#1]
안드로이드 11 이상부턴 앱 구동이 안되는거 같습니다. 이전버전 부터도 안되었을 가능성이 있지만, 이를 확인할 방법이 없기에 안드로이드 11 부터 도입된 scoped storage가 문제가 아닐까 추측합니다.

**Comment by DesignOZ** [comment]
원본 소스 유실 후 가지고있던 APK를 디컴파일 한거라 작동을 장담하기 힘드네요
워낙 예전에 만든거라 새로 만드는게 빠를지도 모를 정도여서 이 저장소에서의 추가적인 작업은 아마 힘들지 않을까 싶습니다

찾아주셔서 대단히 감사합니다

**Comment by PARKasd** [comment]
> 
> 
> 원본 소스 유실 후 가지고있던 APK를 디컴파일 한거라 작동을 장담하기 힘드네요 워낙 예전에 만든거라 새로 만드는게 빠를지도 모를 정도여서 이 저장소에서의 추가적인 작업은 아마 힘들지 않을까 싶습니다
> 
> 찾아주셔서 대단히 감사합니다

아쉽네요... 이런 앱이 구현된게 없어서 찾다 찾다 온건데...
